# Generated by Django 5.2.17 on 2026-10-04 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_initiated', to=settings.AUTH_USER_MODEL)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_a', 'status'], name='accounts_fr_user_a__9bdfcf_idx'), models.Index(fields=['user_b', 'status'], name='accounts_fr_user_b__212a27_idx'), models.Index(fields=['initiated_by', 'status'], name='accounts_fr_initiat_2af8de_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_canonical_friendship_pair'), models.CheckConstraint(condition=models.Q(('user_a__lt', models.F('user_b'))), name='friendship_user_a_less_than_user_b')],
            },
        ),
    ]
