# Generated by Django 5.2.17 on 2026-10-04 03:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text='Emoji or icon identifier', max_length=20)),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF5733)', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cluster_radius_m', models.FloatField(default=200.0, help_text='Radius for visual clustering (meters)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('join_suggestion_radius_m', models.FloatField(default=500.0, help_text='Radius for showing join suggestions (meters)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('self_start_enabled', models.BooleanField(default=True)),
                ('qr_join_enabled', models.BooleanField(default=True)),
                ('gps_tracking_enabled', models.BooleanField(default=False)),
                ('auto_stop_enabled', models.BooleanField(default=True)),
                ('auto_stop_radius_m', models.FloatField(default=100.0, help_text='Distance threshold for auto-stop (meters)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('auto_stop_grace_seconds', models.PositiveIntegerField(default=300, help_text='Time allowed outside radius before stopping')),
                ('default_xp', models.PositiveIntegerField(default=10)),
                ('heat_weight_multiplier', models.FloatField(default=1.0, help_text='Multiplier for map heat visualization', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal'), ('duration', 'Duration'), ('boolean', 'Boolean')], default='integer', max_length=20)),
                ('aggregation', models.CharField(choices=[('sum', 'Sum'), ('max', 'Max'), ('average', 'Average'), ('latest', 'Latest')], default='sum', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Only one primary metric allowed per activity')),
                ('leaderboard_enabled', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=False)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('xp_weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='activities.activitytype')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('activity_type', 'slug'), name='unique_metric_slug_per_activity'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('activity_type',), name='unique_primary_metric_per_activity')],
            },
        ),
    ]
