# Generated by Django 5.2.17 on 2026-10-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activitysession_participation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='activities.activitymetric')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_values', to='activities.participation')),
            ],
            options={
                'unique_together': {('participation', 'metric')},
            },
        ),
    ]
