# Generated by Django 5.2.17 on 2026-10-04 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_gravityevent_eventreward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonRewardAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('badge_awarded', models.BooleanField(default=False)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonRewardRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rank', models.PositiveIntegerField(help_text='Inclusive minimum rank (e.g., 1)')),
                ('max_rank', models.PositiveIntegerField(help_text='Inclusive maximum rank (e.g., 3)')),
                ('xp_bonus', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('metric_name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='gravityevent',
            name='event_ends_after_start',
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='reason',
            field=models.CharField(choices=[('participation', 'Participation'), ('streak', 'Streak'), ('badge', 'Badge'), ('event', 'Event'), ('challenge', 'Challenge'), ('season', 'Season'), ('admin', 'Admin'), ('adjustment', 'Adjustment')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='season_ends_after_start'),
        ),
        migrations.AddField(
            model_name='seasonrewardaward',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype'),
        ),
        migrations.AddField(
            model_name='seasonrewardaward',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.season'),
        ),
        migrations.AddField(
            model_name='seasonrewardaward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seasonrewardrule',
            name='activity_type',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all activities', null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype'),
        ),
        migrations.AddField(
            model_name='seasonrewardrule',
            name='badge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.badge'),
        ),
        migrations.AddField(
            model_name='seasonrewardrule',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='activities.season'),
        ),
        migrations.AddField(
            model_name='seasonrewardaward',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.seasonrewardrule'),
        ),
        migrations.AddField(
            model_name='seasonstanding',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_standings', to='activities.activitytype'),
        ),
        migrations.AddField(
            model_name='seasonstanding',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='activities.season'),
        ),
        migrations.AddField(
            model_name='seasonstanding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_standings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='seasonrewardaward',
            constraint=models.UniqueConstraint(fields=('season', 'rule', 'user', 'activity_type'), name='unique_season_reward_award'),
        ),
        migrations.AddConstraint(
            model_name='seasonstanding',
            constraint=models.UniqueConstraint(fields=('season', 'activity_type', 'user'), name='unique_season_standing'),
        ),
    ]
