# Generated by Django 5.2.17 on 2026-10-04 11:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_friendchallenge_challengereward_challengeparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='auto_stop_mode',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('anchor_radius', 'Anchor Radius'), ('inactivity', 'Inactivity')], default='anchor_radius', help_text='Mode governing auto-stop behavior', max_length=20),
        ),
        migrations.AddField(
            model_name='participation',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
